### ISSUE TITLE
unable to charge hardware preview unit

### ISSUE THREAD

**Issue by dmah42** [curiouschip/pip#10]
i have left the pip without charge for a few weeks after initially setting it up.  i have been trying to charge it all day today (~5 hours) and i cannot get any response from it.  it does not turn on, nor does it show battery status.

any guidance welcome, but it seems to be a dead pip.

**Comment by sukhvirdhillon** [comment]
Hi Dominic,

Sorry to hear of the trouble you are having with your Pip. We are sending out v1 of the Pip software next week and are looking forward to your initial feedback.

With regards to getting Retropie running, we have some instructions on our Discord channel, which you can access using the following link: https://discord.gg/ry7wdpvx <https://discord.gg/ry7wdpvx>

With regards to getting your Pip running, please see notes below:

- Before doing any of the below, press and hold the middle button and left button on your Pip together for at least 5 seconds. This does a hard reset on your Pip.
- Make sure you are using the supplied cable to charge Pip. Any cable you use MUST be rated for at least 1 Amp. Inferior quality cables can damage your Pip.
- Please make sure you are using a wall adapter to charge Pip, capable of supplying at least 1 amp. Your computer can only supply a maximum of 500mA when charging and your Pip may draw considerable less than this when charging.
- Make sure the MicroUSB connector is not loose or damaged on your Pip.
- When you plug the charging cable in, you should see a small LED tun on on the reverse of your Pip, just above the sticker. This indicates that Pip is charging. If this does not turn on, Pip is not drawing any power, which could be either due to a faulty power supply, or a damaged MicroUSB connector.
- Your Pip must be left for at least 10 minutes for a small charge to build in the battery. A fully drained battery will start off with a trickle charge under a certain amount of charge is reached, before it starts to charge at the full rate. Tapping the middle button after 10 minutes should briefly flash the LEDs red, to show that Pip does not yet have sufficient current to power up. Leaving it for a further 10 minutes should give you the minimum charge to boot.

If your Pip still fails to charge or boot after following the above instructions, you will need to send it back for further investigation and a free repair will be carried out where necessary, as long as it has not been damaged by the user. 

Hope this helps and look forward to hearing back.

Best regards,

Sukhvir

**Comment by dmah42** [comment]
the PIP is not drawing any power.  i have used the supplied cable, plugged into a wall charger, and confirmed that no LED lights up.

Please let me know how i can initiate the repair/replacement process.  It certainly hasn't been damaged: i've booted it once to set it up, and then it's been in a drawer since.

**Comment by sukhvirdhillon** [comment]
Hi Dominic,

One final thing to check please. Can you please confirm the status of the LED on the back of pip beside the battery? 

- If it is on, it is charging (although you have confirmed this is not the case).
- If it is blinking, no battery is detected and the battery connector may have come loose (I can guide you through how to resolve this, or happy for you to send it back and I can fix it).
- If it is off, there is a problem that needs further investigation and needs to be sent back.

If it needs to be sent back for repair, please put it in the original packing and send it to:

Curious Chip Ltd
8 Kelvinside Gardens
Glasgow
G20 6BB

Thanks,

Sukhvir

**Comment by dmah42** [comment]
it's off entirely.  i don't have the original packing but i'm happy to send it back well padded.

**Comment by sukhvirdhillon** [comment]
That’s fine Dominic. Please package it as securely as you can and send it back.
